Made Footer annd Navbar
Advay-NIT-Silchar/Advay-website-nextjs pull request #4
Opened 2024-07-03 11:55 UTC by Prizag

2024-08-14 17:23 UTC, advay-nits commented
First run "pnpm i" once and then push again

2024-08-14 17:33 UTC, Prizag commented
runned pnpm i

2024-09-04 08:24 UTC, advay-nits commented
![image](https://github.com/user-attachments/assets/0cbf2295-532d-42c3-a90e-f8cc3c860959)

remove the horizontal scroll-bar

2024-09-28 18:55 UTC, Prizag commented
Removed the horizontal scollbar

2024-10-05 05:33 UTC, advay-nits requested changes
Also decrease the height of the image at footer

2024-10-05 05:33 UTC, advay-nits commented on src/app/components/Navbar.jsx
> +              <div className="ml-4 flex items-center space-x-4">
create an array of objects for navlinks. map over the array to render the links. Also use Link component of Nextjs instead of anchor tag.

2024-10-05 05:34 UTC, advay-nits requested changes
create an array of objects for navlinks. map over the array to render the links. Also use Link component of Nextjs instead of anchor tag.

2024-10-14 15:15 UTC, Prizag commented
updated Navbar.jsx

2024-10-15 19:12 UTC, Ruler45 approved these changes

2024-10-16 07:08 UTC, merged